//
//  AmbianceSound.swift
//  NoNonsenseMeditation
//
//  AUTO-GENERATED FILE - DO NOT EDIT
//  Generated by: generate_ambiance_sounds.py
//  Source: Resources/ambiance_sounds.json
//

import Foundation

/// Represents an ambiance sound configuration for meditation sessions
/// Loaded from ambiance_sounds.json at build time
struct AmbianceSound: Identifiable, Codable, Sendable, Hashable {
    
    // MARK: - Properties
    
    /// Unique identifier for the sound (used for UserDefaults storage)
    let id: String
    
    /// User-facing display name
    let displayName: String
    
    /// SF Symbol icon name
    let iconName: String
    
    /// Short description of the sound
    let description: String
    
    /// Filename for the audio resource (without extension)
    let filename: String?
    
    /// File extension for the audio resource
    let fileExtension: String?
    
    /// Whether this sound requires an audio file from the bundle
    let requiresFile: Bool
    
    /// Whether this sound uses the user's music library
    let isUserLibrary: Bool
    
    // MARK: - Computed Properties
    
    /// Whether this sound uses the user's music library
    var usesUserLibrary: Bool { isUserLibrary }
}

// MARK: - Ambiance Sound Loader

/// Loads ambiance sounds from the generated configuration
enum AmbianceSoundLoader {
    
    /// All available ambiance sounds
    /// This array is generated at build time from ambiance_sounds.json
    static let allSounds: [AmbianceSound] = [
    AmbianceSound(id: "none", displayName: "No Background Sound", iconName: "speaker.slash", description: "Silence", filename: nil, fileExtension: nil, requiresFile: false, isUserLibrary: false),
    AmbianceSound(id: "brown_noise", displayName: "Brown Noise", iconName: "waveform", description: "Deep ambient noise", filename: "brown_noise", fileExtension: "m4a", requiresFile: true, isUserLibrary: false),
    AmbianceSound(id: "library_noise", displayName: "Library Ambience", iconName: "building.2", description: "Quiet study atmosphere", filename: "library_noise", fileExtension: "m4a", requiresFile: true, isUserLibrary: false),
    AmbianceSound(id: "wind_chimes", displayName: "Wind Chimes", iconName: "wind", description: "Gentle chimes", filename: "wind_chimes", fileExtension: "m4a", requiresFile: true, isUserLibrary: false),
    AmbianceSound(id: "user_library", displayName: "Music Library", iconName: "music.note.list", description: "Play from your library", filename: nil, fileExtension: nil, requiresFile: false, isUserLibrary: true)
    ]
    
    /// Find a sound by its ID
    /// - Parameter id: The unique identifier of the sound
    /// - Returns: The sound with the given ID, or nil if not found
    static func sound(withId id: String) -> AmbianceSound? {
        allSounds.first { $0.id == id }
    }
    
    /// The "none" sound option (silence)
    static let none: AmbianceSound = allSounds[0]
    
    /// The user library sound option
    static let userLibrary: AmbianceSound? = allSounds.first { $0.isUserLibrary }
}

// MARK: - UserDefaults Persistence

extension AmbianceSound {
    /// UserDefaults key for storing selected background sound
    private static let userDefaultsKey = "selectedBackgroundSound"
    
    /// Save the background sound ID to UserDefaults
    func saveToUserDefaults() {
        UserDefaults.standard.set(id, forKey: Self.userDefaultsKey)
    }
    
    /// Load the background sound from UserDefaults
    /// - Returns: The saved sound, or .none if not found
    static func loadFromUserDefaults() -> AmbianceSound {
        guard let rawValue = UserDefaults.standard.string(forKey: userDefaultsKey),
              let sound = AmbianceSoundLoader.sound(withId: rawValue) else {
            return AmbianceSoundLoader.none
        }
        return sound
    }
}
